### ISSUE TITLE
Bug in ogdf

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#5] opened 2014-08-21 12:55 UTC
qMedusa: /home/ivan/projects/medisa_project/ogdf/include/ogdf/basic/NodeArray.h:145: T& ogdf::NodeArray<T>::operator[](ogdf::node) [with T = double; ogdf::node = ogdf::NodeElement*]: 
An assertion «v != 0 && v->graphOf() == m_pGraph» missed.
Аварийный останов (сделан дамп памяти)

1)open any  file
2)click To log window
3)press Ctrl+F

CFG view fall too...((

**Comment by wisk** [comment] 2014-08-21 19:33
Hi @gunmetal313, and thanks for reporting this issue.

Unfortunately, I'm unable to reproduce the bug (tested on Windows/Debug version).
Could you provide more info about your configuration? (arch, os, build_type, branch, ...)

**Comment by ivan-kulikov-dev** [comment] 2014-08-21 21:24
ohhh.Ctrl+F is CFG view.On master branch all ok.It where some falls CFG view on dev branch.But all ok on current commit https://github.com/wisk/medusa/commit/6df15e7d6fdd6ad8c529f00420d30b087f58679b :)

**Comment by wisk** [comment] 2014-08-22 09:34
I suspect the assert is triggered when there's nothing to display (i.e. no block). This line https://github.com/wisk/medusa/blob/dev/src/ui/qt/ControlFlowGraphScene.cpp#L30 should fix the problem since **Medusa::BuildControlFlowGraph** (https://github.com/wisk/medusa/blob/dev/src/core/analyzer.cpp#L934) should return false if the CFG is empty.
I close this issue for now, but if you're still able to trigger this assert, feel free to notify me, I'll re-open it.

**Closed as completed by wisk** 2014-08-22 09:34 UTC
Labels: bug
